from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from config import LabConfig, load_config
from memory_store import estimate_tokens
from model_provider import build_chat_model


@dataclass
class SessionState:
    messages: list[dict[str, str]] = field(default_factory=list)
    token_usage: int = 0
    prompt_tokens_processed: int = 0


class BaselineAgent:
    """Baseline Agent (Agent A).

    Characteristics:
    - Maintains within-session short-term memory only.
    - No persistent User.md storage.
    - Forgets all facts across different thread_ids.
    - Serves as an un-augmented baseline comparison for the advanced agent.
    """

    def __init__(self, config: LabConfig | None = None, force_offline: bool = False) -> None:
        self.config = config or load_config()
        self.force_offline = force_offline
        self.sessions: dict[str, SessionState] = {}
        self.langchain_agent = self._maybe_build_langchain_agent()

    def reply(self, user_id: str, thread_id: str, message: str) -> dict[str, Any]:
        """Processes a message and returns the response with token usage metrics."""
        if self.langchain_agent is not None and not self.force_offline:
            try:
                return self._reply_live(thread_id, message)
            except Exception:
                # Fallback to deterministic offline mode on provider or network failure
                return self._reply_offline(thread_id, message)
        return self._reply_offline(thread_id, message)

    def token_usage(self, thread_id: str | None = None) -> int:
        """Returns the cumulative tokens generated by the agent (completion tokens)."""
        if thread_id is not None:
            return self.sessions.get(thread_id, SessionState()).token_usage
        return sum(s.token_usage for s in self.sessions.values())

    def prompt_token_usage(self, thread_id: str | None = None) -> int:
        """Returns the cumulative prompt context tokens processed by the agent."""
        if thread_id is not None:
            return self.sessions.get(thread_id, SessionState()).prompt_tokens_processed
        return sum(s.prompt_tokens_processed for s in self.sessions.values())

    def compaction_count(self, thread_id: str | None = None) -> int:
        """Baseline agent does not have compact memory, returns 0."""
        return 0

    def _reply_offline(self, thread_id: str, message: str) -> dict[str, Any]:
        """Generates deterministic responses for offline benchmarking."""
        session = self.sessions.setdefault(thread_id, SessionState())

        # Baseline carries the entire uncompressed message history of this thread
        history_tokens = sum(estimate_tokens(m["content"]) for m in session.messages)
        new_msg_tokens = estimate_tokens(message)
        prompt_tokens = history_tokens + new_msg_tokens

        # Check if this thread has prior history
        is_fresh_thread = len(session.messages) == 0

        # In a new thread, baseline has no memory and cannot answer recall questions
        lower = message.lower()
        if is_fresh_thread and (lower.endswith("?") or any(k in lower for k in ["nhắc lại", "là ai", "ở đâu", "gì"])):
            reply_text = (
                "Chào bạn! Vì đây là cuộc trò chuyện mới và mình không có hệ thống lưu trữ thông tin "
                "dài hạn, mình chưa biết thông tin này của bạn."
            )
        else:
            reply_text = "Mình đã ghi nhận thông tin của bạn trong phiên trò chuyện này."

        agent_tokens = estimate_tokens(reply_text)

        # Update session state
        session.messages.append({"role": "user", "content": message})
        session.messages.append({"role": "assistant", "content": reply_text})
        session.token_usage += agent_tokens
        session.prompt_tokens_processed += prompt_tokens

        return {
            "content": reply_text,
            "reply": reply_text,
            "response": reply_text,
            "agent_tokens": agent_tokens,
            "prompt_tokens": prompt_tokens,
        }

    def _reply_live(self, thread_id: str, message: str) -> dict[str, Any]:
        """Sends conversation turns to the configured LangChain chat model."""
        session = self.sessions.setdefault(thread_id, SessionState())
        from langchain_core.messages import AIMessage, HumanMessage, SystemMessage

        chat_messages = [
            SystemMessage(
                content="Bạn là một AI assistant hữu ích. Bạn chỉ ghi nhớ thông tin trong phiên trò chuyện hiện tại."
            )
        ]
        for m in session.messages:
            if m["role"] == "user":
                chat_messages.append(HumanMessage(content=m["content"]))
            else:
                chat_messages.append(AIMessage(content=m["content"]))
        chat_messages.append(HumanMessage(content=message))

        prompt_tokens = sum(estimate_tokens(getattr(m, "content", "")) for m in chat_messages)

        response = self.langchain_agent.invoke(chat_messages)
        reply_text = response.content if hasattr(response, "content") else str(response)

        agent_tokens = estimate_tokens(reply_text)
        if hasattr(response, "usage_metadata") and response.usage_metadata:
            prompt_tokens = response.usage_metadata.get("input_tokens", prompt_tokens)
            agent_tokens = response.usage_metadata.get("output_tokens", agent_tokens)

        session.messages.append({"role": "user", "content": message})
        session.messages.append({"role": "assistant", "content": reply_text})
        session.token_usage += agent_tokens
        session.prompt_tokens_processed += prompt_tokens

        return {
            "content": reply_text,
            "reply": reply_text,
            "response": reply_text,
            "agent_tokens": agent_tokens,
            "prompt_tokens": prompt_tokens,
        }

    def _maybe_build_langchain_agent(self) -> Any:
        """Initializes the chat model for live LLM mode if credentials are present."""
        if self.force_offline:
            return None
        try:
            provider = self.config.model.provider.lower()
            if provider != "ollama" and not self.config.model.api_key:
                return None
            return build_chat_model(self.config.model)
        except Exception:
            return None
